airbnb:
  outputs:
    dev:
      account: "{{env_var('SNOWFLAKE_ACCOUNT')}}"
      database: AIRBNB
      private_key: "{{env_var('PRIVATE_KEY')}}"
      private_key_passphrase: "{{env_var('PRIVATE_KEY_PASSPHRASE')}}"
      role: TRANSFORM
      schema: DBT_{{env_var('DBT_ENV_NAME') | upper | trim}}
      threads: 4
      type: snowflake
      user: "{{env_var('DBT_USER')}}"
      warehouse: COMPUTE_WH
    prod:
      account: "{{env_var('SNOWFLAKE_ACCOUNT')}}"
      database: AIRBNB
      private_key: "{{env_var('PRIVATE_KEY')}}"
      private_key_passphrase: "{{env_var('PRIVATE_KEY_PASSPHRASE')}}"
      role: TRANSFORM
      schema: PROD
      threads: 4
      type: snowflake
      user: "{{env_var('DBT_USER')}}"
      warehouse: COMPUTE_WH
    staging:
      account: "{{env_var('SNOWFLAKE_ACCOUNT')}}"
      database: AIRBNB
      private_key: "{{env_var('PRIVATE_KEY')}}"
      private_key_passphrase: "{{env_var('PRIVATE_KEY_PASSPHRASE')}}"
      role: TRANSFORM
      schema: STAGING
      threads: 4
      type: snowflake
      user: "{{env_var('DBT_USER')}}"
      warehouse: COMPUTE_WH
  target: dev
airstats:
  outputs:
    dev:
      account: "{{env_var('SNOWFLAKE_ACCOUNT')}}"
      database: AIRSTATS
      private_key: "{{env_var('PRIVATE_KEY')}}"
      private_key_passphrase: "{{env_var('PRIVATE_KEY_PASSPHRASE')}}"
      role: TRANSFORM
      schema: DBT_{{env_var('DBT_ENV_NAME') | upper | trim}}
      threads: 4
      type: snowflake
      user: "{{env_var('DBT_USER')}}"
      warehouse: COMPUTE_WH
  target: dev
